In [10]:
import torch

freqs = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
end = 10

def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
    freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device, dtype=torch.float32)
    freqs = torch.outer(t, freqs)
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    return freqs_cis

In [11]:
freqs_cis = precompute_freqs_cis(10, 10)

In [12]:
freqs_cis

tensor([[ 1.0000+0.0000e+00j,  1.0000+0.0000e+00j,  1.0000+0.0000e+00j,
          1.0000+0.0000e+00j,  1.0000+0.0000e+00j],
        [ 0.5403+8.4147e-01j,  0.9875+1.5783e-01j,  0.9997+2.5116e-02j,
          1.0000+3.9811e-03j,  1.0000+6.3096e-04j],
        [-0.4161+9.0930e-01j,  0.9502+3.1170e-01j,  0.9987+5.0217e-02j,
          1.0000+7.9621e-03j,  1.0000+1.2619e-03j],
        [-0.9900+1.4112e-01j,  0.8891+4.5775e-01j,  0.9972+7.5285e-02j,
          0.9999+1.1943e-02j,  1.0000+1.8929e-03j],
        [-0.6536-7.5680e-01j,  0.8057+5.9234e-01j,  0.9950+1.0031e-01j,
          0.9999+1.5924e-02j,  1.0000+2.5238e-03j],
        [ 0.2837-9.5892e-01j,  0.7021+7.1207e-01j,  0.9921+1.2526e-01j,
          0.9998+1.9904e-02j,  1.0000+3.1548e-03j],
        [ 0.9602-2.7942e-01j,  0.5809+8.1396e-01j,  0.9887+1.5014e-01j,
          0.9997+2.3884e-02j,  1.0000+3.7857e-03j],
        [ 0.7539+6.5699e-01j,  0.4452+8.9544e-01j,  0.9846+1.7493e-01j,
          0.9996+2.7864e-02j,  1.0000+4.4167e-03j],
        

In [15]:
def precompute_freqs_cis1(ranges: dict, dim: int):
    freqs_list = []
    for range_, theta in ranges.items():
        start, end = range_
        freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
        t = torch.arange(start, end, device=freqs.device, dtype=torch.float32)
        freqs = torch.outer(t, freqs)
        freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
        freqs_list.append(freqs_cis)

    # Concatenate the frequency tensors along the time dimension
    freqs_concatenated = torch.cat(freqs_list, dim=0)
    return freqs_concatenated

In [16]:
ranges = {(0, 10): 10000}
freqs_cis1 = precompute_freqs_cis1(ranges, 10)

In [17]:
if torch.allclose(freqs_cis, freqs_cis1):
    print("The two methods are equivalent")
else:
    print("The two methods are not equivalent")

The two methods are equivalent


In [18]:
test = [1]
test = test * 3

In [19]:
test

[1, 1, 1]

In [24]:
import torch
from torch import Tensor
def push_to_tensor_alternative(tensor, x):
    return torch.cat((tensor[1:], Tensor([x])))

In [25]:


tensor = Tensor([1,2,3,4])
tensor

tensor([1., 2., 3., 4.])

In [26]:
tensor = push_to_tensor_alternative(tensor, 5)
tensor

tensor([2., 3., 4., 5.])

In [27]:
tensor = push_to_tensor_alternative(tensor, 6)
tensor

tensor([3., 4., 5., 6.])

In [31]:
queue_k = torch.randn(5, 10, 2)
queue_k


tensor([[[-0.4741, -0.6609],
         [ 0.1383,  2.2300],
         [ 0.3952,  0.6535],
         [ 0.4807,  1.3275],
         [-0.4744,  2.0742],
         [-0.7501, -0.2126],
         [-0.9224,  0.3270],
         [ 0.1486,  1.0093],
         [ 0.0469, -2.2629],
         [ 0.5814, -1.1449]],

        [[-0.3501,  1.3279],
         [-0.0095,  0.1492],
         [ 1.0002,  0.2290],
         [-0.9867,  0.6406],
         [-0.3176, -0.7281],
         [-0.9368,  1.0395],
         [-0.6474,  1.7635],
         [-0.5570, -0.2907],
         [ 0.1889, -0.9212],
         [-0.4432,  0.0905]],

        [[ 0.3901, -0.5778],
         [ 0.7738, -1.5035],
         [ 0.7590, -0.9173],
         [ 0.7240, -0.3338],
         [ 0.8984, -1.1061],
         [-1.0088,  0.6361],
         [-0.5551, -0.5749],
         [ 0.2005,  0.7975],
         [-0.0142, -0.5320],
         [ 0.1507, -0.2634]],

        [[-0.1233, -1.5469],
         [-1.4706, -0.6459],
         [ 2.1241, -0.0952],
         [-1.3966, -0.2660],
        

In [34]:
queue_k[:, 3:1:-1, :]

ValueError: step must be greater than zero

In [45]:
start = -5
end = -1

t = torch.arange(start, end, dtype=torch.float32)

In [46]:
t

tensor([-5., -4., -3., -2.])

In [49]:
fix_t = 2
start = 0
end = 40

t = torch.full((end - start,), fix_t, dtype=torch.float32)

In [50]:
t

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2.])

In [51]:
t.shape

torch.Size([40])

In [53]:
def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
    freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device, dtype=torch.float32)
    freqs = torch.outer(t, freqs)
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    return freqs_cis

a = precompute_freqs_cis(2, 10)
a

tensor([[ 1.0000+0.0000j],
        [ 0.5403+0.8415j],
        [-0.4161+0.9093j],
        [-0.9900+0.1411j],
        [-0.6536-0.7568j],
        [ 0.2837-0.9589j],
        [ 0.9602-0.2794j],
        [ 0.7539+0.6570j],
        [-0.1455+0.9894j],
        [-0.9111+0.4121j]])